# Copyright (c) 2024, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

---
networks:
  quickstart:
    external: true
    name: ${DOCKER_NETWORK}

services:
  create-app-install-request:
    build: .
    container_name: create-app-install-request
    volumes:
      - ./scripts/start.sh:/app/start.sh
      - ./scripts/create-app-install-request.sh:/app/create-app-install-request.sh
      - ./scripts/simulate-user-input.sh:/app/simulate-user-input.sh
      - ./../utils.sh:/app/utils.sh
    environment:
      - LEDGER_API_ADMIN_USER=${LEDGER_API_ADMIN_USER}
      - AUTH_APP_PROVIDER_CLIENT_ID=${AUTH_APP_PROVIDER_CLIENT_ID}
      - APP_USER_USER_ID=${AUTH_APP_USER_CLIENT_ID}
      - AUTH_APP_USER_CLIENT_ID=${AUTH_APP_USER_CLIENT_ID}
      - WALLET_ADMIN_USER=${WALLET_ADMIN_USER}
    command: /app/start.sh
    networks:
      - ${DOCKER_NETWORK}