x-ui-config:
  &ui-config
    environment:
      - SPLICE_APP_UI_NETWORK_NAME=Splice
      - SPLICE_APP_UI_NETWORK_FAVICON_URL=https://www.hyperledger.org/hubfs/hyperledgerfavicon.png
      - SPLICE_APP_UI_AMULET_NAME=Amulet
      - SPLICE_APP_UI_AMULET_NAME_ACRONYM=AMT
      - SPLICE_APP_UI_NAME_SERVICE_NAME=Amulet Name Service
      - SPLICE_APP_UI_NAME_SERVICE_NAME_ACRONYM=ANS

services:
  wallet-web-ui:
      <<: *ui-config
  ans-web-ui:
      <<: *ui-config
